### PR TITLE
Update supported MP versions for TomEE

### PR DESCRIPTION
**Pull request by dblevins**
Looks like I missed expanding the MP version enum list for TomEE

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
> Hi @dblevins , could you [update the Wiki](https://wiki.eclipse.org/MicroProfile/Implementation) before we merge this, please? TomEE 8.0.0-M3 is not even listed there...
> 
> THX
> 
> K.

HI, thanks for the feedback.
I sent today a request to update (https://wiki.eclipse.org/MicroProfile/Implementation)  for 2.2 and it's waiting for moderation.

**Comment by Karm** [comment]
@cesarhernandezgt, @Emily-Jiang, @cealsair
Guys, what is holding the Wiki update?
It has been many days already. I guess it is not that complicated; TomEE 8.0.0-M3 either passes TCK and should be listed or it doesn't and we should close/postpone the PR. 

I find it somewhat confusing: [Wiki shows TomEE 8.0.0-M3](https://wiki.eclipse.org/index.php?title=MicroProfile/Implementation&diff=433782&oldid=433588) edit as *In Progress* for MP 3.0, while this PR is about MP21. MP21 does not have any Wiki listing for TomEE 8.0.0-M3.

Are you sure @cesarhernandezgt  you edited the MP21 row on the wiki? 

> HI @Karm , thanks for the feedback.
> I sent today a request to update (https://wiki.eclipse.org/MicroProfile/Implementation) for 2.2
> and it's waiting for moderation.

This PR is about MP21 not MP22.

Thank you for helping me understand what is the situation with TomEE and MP21 and MP22.

As soon as it is clear, we can merge the PR.

**Comment by Karm** [comment]
@cesarhernandezgt, @Emily-Jiang, @cealsair
Guys, what is holding the Wiki update?
It has been many days already. I guess it is not that complicated; TomEE 8.0.0-M3 either passes TCK and should be listed or it doesn't and we should close/postpone the PR. 

I find it somewhat confusing: [Wiki shows TomEE 8.0.0-M3](https://wiki.eclipse.org/index.php?title=MicroProfile/Implementation&diff=433782&oldid=433588) edit as *In Progress* for MP 3.0, while this PR is about MP21. MP21 does not have any Wiki listing for TomEE 8.0.0-M3.

Are you sure @cesarhernandezgt  you edited the MP21 row on the wiki? 

> HI @Karm , thanks for the feedback.
> I sent today a request to update (https://wiki.eclipse.org/MicroProfile/Implementation) for 2.2
> and it's waiting for moderation.

This PR is about MP21 not MP22.

Thank you for helping me understand what is the situation with TomEE and MP21 and MP22.

As soon as it is clear, we can merge the PR.

**Comment by Karm** [comment]
@dblevins  ```This branch has conflicts that must be resolved```

**Comment by Emily-Jiang** [comment]
I did not see any pending wiki update for adding TomEE 8.0.0-M3 and I emailed @cesarhernandezgt but I have not got any confirmation. @dblevins can you chase it up about the wiki update and resolve the merge conflicts so that we can get TomEE 8.0.0-M3 showing up on the list?

**Comment by cesarhernandezgt** [comment]
Hi @Karm and @Emily-Jiang .

I did again the update and also fixed the In progress version. I hope this time my edit is visible for the moderators of that page. Following is the sequence of tests I did this time.:

Screen Shot 2019-08-24 at 22 59 08

Screen Shot 2019-08-24 at 23 00 22

Screen Shot 2019-08-24 at 23 00 35

**Comment by Karm** [comment]
@cesarhernandezgt I set out to merge the PR, but it is not updated; it has wrong MP version in it, 21 instead of 22 and there are conflicts. Since @dblevins is probably unavailable; could you create a new PR with the changes, please? It is just editing the MP versions since the TomEE version TomEE 8.0.0-M3 is merged already.  Thx.

**Comment by Emily-Jiang** [comment]
I'm closing this PR as @cesarhernandezgt has done the merging and created a new PR #200 , which was merged now.

**Pull request closed without merging**
