### PR TITLE
add depdenabot

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>
Fixes: #407

### CODE REVIEW

**Review by rdebusscher — COMMENTED** [review]
Not sure we should update dependencies automatically as it can break things. Getting notified is a good thing but we should keep control of the dependencies.

**Comment by Emily-Jiang** [comment]
> Not sure we should update dependencies automatically as it can break things. Getting notified is a good thing but we should keep control of the dependencies.

Yes, we should review the PR created by dependabot before merging for sure.

**Comment by rdebusscher** [comment]
We have today already these PRs from dependabot. So what is this config for?

**Comment by Emily-Jiang** [comment]
This is enabled automatically.

**Pull request closed without merging**
