### PR TITLE
TomEE MP Support

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by rdebusscher** [comment]
Hi,

Great to see that you included TomEE into the tool.

Can you add `(Milestone)` to the description within the dropdown (second value in the SupportedServer enum)

I'll de other checks, but looks OK at first sight.

**Comment by radcortez** [comment]
I changed the description to be Apache TomEE 8.0.0-M2. This will be in line with TomEE download page: http://tomee.apache.org/download-ng.html

Hope it is ok like this.

**Comment by rdebusscher** [comment]
Hi Roberto,

The link from the index.html page to the 'system' URLS (metrics, Health, openAPI, ...) are not correct.  Please add the following patch to your PR.

Thx.
[Tomee.patch.txt](https://github.com/eclipse/microprofile-starter/files/2824790/Tomee.patch.txt)

**Comment by radcortez** [comment]
Done! Thank you!

**Pull request merged**
