### PR TITLE
Updated supported MP versions for KumuluzEE

### PR DESCRIPTION
**Pull request by jmezna**

### CODE REVIEW

**Comment by Karm** [comment]
Hi @jmezna, thank you for the PR.
Could you sign the ECA and add amend your commit message to end with: ```Signed-off-by: name <email you used to sign ECA>```, please? You can take a look at our [contributing guide](https://github.com/eclipse/microprofile-starter/blob/master/CONTRIBUTING.md#how-to-contribute) or more detailed guide with screenshots [here](https://github.com/eclipse/microprofile-starter/pull/108#issuecomment-497310175).

**Comment by jmezna** [comment]
Added ECA

**Comment by Karm** [comment]
@jmezna, read the guides I linked about the signature in the commit, please.

**Comment by Karm** [comment]
```
Jan Meznarič did not include the "Signed-off-by footer" which is required for all commits made by a contributor.
```

**Comment by Karm** [comment]
There are no changes but for the MP version bump and it is aligned with [the wiki](https://wiki.eclipse.org/MicroProfile/Implementation) so I merge this PR.   Fixes #175

Watch https://gitter.im/eclipse/microprofile-starter for update on when it goes live on the testing site.

**Pull request merged**
