### PR TITLE
Links to Runtime Home pages and Version release pages. fixes #284

### LINKED ISSUE #284: Create hints for fields: Version, Runtimes, and each Specification
To help developers better understand the MicroProfile Starter, create hints for fields:

- MicroProfile Version.  For example, when hovering over each MP version, or hovering over field name
- MicroProfile Runtimes. For example, when hovering over each runtimes, or hovering over field name
- Each specification under "Examples for specifications". This would give a short description of what the specification does.

Thanks,
Cesar

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Comment by Karm** [comment]
Looks good to me. 

MicroProfile

**Comment by Karm** [comment]
@Emily-Jiang, you can see for yourself here https://test-start.microprofile.io/

**Comment by Emily-Jiang** [comment]
The links look good! Thanks @rdebusscher ! We also need to do the same thing for the specs. Are you going to do it under a separate PR?

**Comment by rdebusscher** [comment]
@Emily-Jiang Yes a separate PR as you liked to have the correct version of the spec related to the MP version.
Which takes some more data to be maintained (and I didn't found the time yet)

**Comment by Emily-Jiang** [comment]
A minor comment: Can we also add a hint to the MicroProfile runtime to say: A list of runtime that supports the chosen MicroProfile version? @rdebusscher

**Pull request merged**
