### PR TITLE
enable liberty tests

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by Karm** [comment]
@Emily-Jiang  You might want to rebase so as it has the PATH fix...

**Comment by Karm** [comment]
Looking at the 1 failed LibertyAll test and its archived test log:

```
Extracting files to /home/runner/wlpExtract/liberty_556231284185/wlp
Successfully extracted all product files.
Launching liberty (Open Liberty 20.0.0.12/wlp-1.0.47.cl201220201111-0736) on OpenJDK 64-Bit Server VM, version 11.0.9.1+1 (en_US)
[AUDIT   ] CWWKE0001I: The server liberty has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWPKI0803A: SSL certificate created in 4.208 seconds. SSL key file: /home/runner/wlpExtract/liberty_556231284185/wlp/usr/servers/liberty/resources/security/public.jks
[AUDIT   ] CWWKS4104A: LTPA keys created in 6.109 seconds. LTPA key file: /home/runner/wlpExtract/liberty_556231284185/wlp/usr/servers/liberty/resources/security/ltpa.keys
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0001I: Application liberty started in 11.727 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, jwt-1.0, microProfile-3.3, monitor-1.0, mpConfig-1.4, mpFaultTolerance-2.1, mpHealth-2.2, mpJwt-1.1, mpMetrics-2.3, mpOpenAPI-1.1, mpOpenTracing-1.3, mpRestClient-1.4, opentracing-1.3, servlet-4.0, ssl-1.0].
[AUDIT   ] CWWKF0011I: The liberty server is ready to run a smarter planet. The liberty server started in 27.656 seconds.
[AUDIT   ] CWWKE0085I: The server liberty is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/
[err] !SESSION 2020-12-10 12:06:41.726 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY com.ibm.ws.threading 4 0 2020-12-10 12:06:41.726
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.io.IOException: Exception in opening zip file: /home/runner/wlpExtract/liberty_556231284185/wlp/lib/com.ibm.ws.threading_1.1.47.jar
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:340)
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.doOpen(ZipBundleFile.java:48)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.open(CloseableBundleFile.java:128)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.lockOpen(CloseableBundleFile.java:77)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.getEntry(CloseableBundleFile.java:261)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathEntry.findEntry(ClasspathEntry.java:195)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:622)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:608)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:588)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:567)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.ibm.ws.threading.internal.FutureMonitorImpl.createFutureWithResult(FutureMonitorImpl.java:130)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.uninstall(WARApplicationHandlerImpl.java:82)
	at com.ibm.ws.app.manager.internal.statemachine.StopAction.execute(StopAction.java:83)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1342)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1182)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:905)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: /home/runner/wlpExtract/liberty_556231284185/wlp/lib/com.ibm.ws.threading_1.1.47.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:322)
	... 23 more
[ERROR   ] CWWKZ0010E: An exception occurred while stopping the application liberty. The exception message was: java.lang.NoClassDefFoundError: com/ibm/ws/threading/internal/ImmediateFutureImpl
[AUDIT   ] CWWKE0036I: The server liberty stopped after 35.207 seconds.
```

**Comment by Karm** [comment]
@Emily-Jiang Should I be deleting `wlpExtract`  dir between tests?

**Comment by Emily-Jiang** [comment]
> @Emily-Jiang Should I be deleting `wlpExtract` dir between tests?

Yes, please. @Karm

**Comment by Emily-Jiang** [comment]
@Karm @rdebusscher finally the build worked ok. Please review so that we can do a release soon.

**Comment by Karm** [comment]
@Emily-Jiang Could you squash it, please?   What exactly fixed it...? It seems some commits added wlp dir, some removed it again...  it look slike the final diff is my commit with the PATH change + removed `@Ignore`.   I am curious what made the Liberty pass...?

**Comment by Emily-Jiang** [comment]
@Karm it turned out I don't need to set the environment variable so I removed it. I can confirm that my PR did turn on Liberty, as demonstrated by the test log.
`Dec 10, 2020 10:24:40 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing server: LIBERTY, config: EMPTY
Dec 10, 2020 10:24:40 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Downloading...
Dec 10, 2020 10:24:40 PM org.eclipse.microprofile.starter.utils.Commands download
INFO: from http://127.0.0.1:9090/api/project?supportedServer=LIBERTY&artifactId=liberty
Dec 10, 2020 10:24:40 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Build might take many minutes if the whole Internet is being downloaded.
Dec 10, 2020 10:25:10 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Running...
Dec 10, 2020 10:25:10 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing web page content...
Dec 10, 2020 10:25:22 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Terminate and scan logs...
Dec 10, 2020 10:25:25 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Gonna wait for ports closed...
Dec 10, 2020 10:25:25 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing server: LIBERTY, config: ALL
Dec 10, 2020 10:25:25 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Downloading...
Dec 10, 2020 10:25:25 PM org.eclipse.microprofile.starter.utils.Commands download
INFO: from http://127.0.0.1:9090/api/project?supportedServer=LIBERTY&selectAllSpecs=true&artifactId=liberty
Dec 10, 2020 10:25:25 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Build might take many minutes if the whole Internet is being downloaded.
Dec 10, 2020 10:26:05 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Running...
Dec 10, 2020 10:26:05 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing web page content...
Dec 10, 2020 10:26:31 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Terminate and scan logs...
Dec 10, 2020 10:26:37 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Gonna wait for ports closed...
Dec 10, 2020 10:26:37 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing server: LIBERTY, config: ALL_BUT_JWT_REST
Dec 10, 2020 10:26:37 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Downloading...
Dec 10, 2020 10:26:37 PM org.eclipse.microprofile.starter.utils.Commands download
INFO: from http://127.0.0.1:9090/api/project?supportedServer=LIBERTY&selectedSpecs=CONFIG&selectedSpecs=FAULT_TOLERANCE&selectedSpecs=HEALTH_CHECKS&selectedSpecs=METRICS&selectedSpecs=OPEN_TRACING&selectedSpecs=OPEN_API&artifactId=liberty
Dec 10, 2020 10:26:37 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Build might take many minutes if the whole Internet is being downloaded.
Dec 10, 2020 10:26:59 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Running...
Dec 10, 2020 10:26:59 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing web page content...
Dec 10, 2020 10:27:11 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Terminate and scan logs...
Dec 10, 2020 10:27:14 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Gonna wait for ports closed...
Dec 10, 2020 10:27:14 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing server: LIBERTY, config: JWT_REST
Dec 10, 2020 10:27:14 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Downloading...
Dec 10, 2020 10:27:14 PM org.eclipse.microprofile.starter.utils.Commands download
INFO: from http://127.0.0.1:9090/api/project?supportedServer=LIBERTY&selectedSpecs=JWT_AUTH&selectedSpecs=REST_CLIENT&artifactId=liberty
Dec 10, 2020 10:27:14 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Build might take many minutes if the whole Internet is being downloaded.
Dec 10, 2020 10:27:50 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Running...
Dec 10, 2020 10:27:50 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Testing web page content...
Dec 10, 2020 10:28:14 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Terminate and scan logs...
Dec 10, 2020 10:28:21 PM org.eclipse.microprofile.starter.TestMatrixTest testRuntime
INFO: Gonna wait for ports closed...`

**Comment by Emily-Jiang** [comment]
Anyway, I have squshed the commits. You can see the final result via `File changes`, which always give you the final version of the commits.

**Review by Karm — APPROVED** [review]

**Pull request merged**
