### PR TITLE
Add MP 4.0 and the current implementations supporting it. Fixes #409

### LINKED ISSUE #409: Configure MP 4.0 with initial implementations
Define MP 4.0 in the starter.
Not updating the examples for MP 4.0, that is done later in #357

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Comment by Emily-Jiang** [comment]
@rdebusscher unfortunately your PR failed the build. Did you test it locally? For Open Liberty, I will have to update the jeager client version. I will actually comment on your PR to ask you to update the version instead to work with Open Tracing 0.33.

**Comment by Emily-Jiang** [comment]
@rdebusscher in pom-server.xml, please replace the following under `liberty` profile 
```
<dependencies>
                    <dependency>
                        <groupId>io.jaegertracing</groupId>
                        <artifactId>jaeger-client</artifactId>
                        <version>0.34.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-jdk14</artifactId>
                        <version>1.7.25</version>
                    </dependency>
            </dependencies>

```

with this
`
<dependency>
    <groupId>io.jaegertracing</groupId>
    <artifactId>jaeger-client</artifactId>
    <version>1.5.0</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>1.7.30</version>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-jdk14</artifactId>
    <version>1.7.30</version>
</dependency>`

**Review by Emily-Jiang — CHANGES_REQUESTED** [review]
Please address my comments https://github.com/eclipse/microprofile-starter/pull/410#issuecomment-805342674 
and fix the build.

**Comment by rdebusscher** [comment]
updated the pom-server.xml file with your changes @Emily-Jiang

**Comment by rdebusscher** [comment]
Testing doesn't work on my machine anymore for some time ...

>java.io.IOException: Cannot run program "unzip"

although unzip program is installed.

**Comment by Emily-Jiang** [comment]
@rdebusscher you can use Open Liberty dev mode to test it out without needing to download the zip.

**Review by Emily-Jiang — APPROVED** [review]

**Pull request merged**
