### PR TITLE
Adds Quarkus to the TS, CircleCI update for TS, whitelists

### PR DESCRIPTION
**Pull request by Karm**
Adds Quarkus to the TS, enables the TS on CircleCI and adds Kumuluzee whitelist for a new error.
Payara also got whitelisted for benign error messages unrelated to Starter (Hazelcast clustering).
Weird Quarkus ```mvn package``` error message **after** a successful build is done; also whitelisted. I was not able to even reproduce this message outside Circle CI...

It is stable and it works now. Tested cca 5 times on Circle CI.

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@Karm can you open an issue to clearly document the issue instead of just adding comments on the PR? In this way, in our milestone we will clearly understand the issues we've fixed.

**Comment by Karm** [comment]
@Emily-Jiang this is a misunderstanding, I did not fix any Payara/Kumuluzee issues, I whitelisted their error messages that poped up on Circle Ci (probably due to networking). This PR adds Quarkus to the TS and it fixes Circle CI setup for the TS.

**Comment by Emily-Jiang** [comment]
@Karm what I meant is to create an issue to document the problem and then create the PR for that issue. In this way, we will have a better view on what changes went in and for what reason.
In this PR, you need to add Quarkus to TS, CircleCI update for TS. Can you explain a bit on the problems on Circle CI etc.

**Comment by Karm** [comment]
@Emily-Jiang  O.K., I went and created #270, #271, #272. 

They are all interconnected - they are about bringing TS to the Circle CI env. It is perfectly fine to have this change in 1 PR and if there are no technical objections I would really like to have it merged.

If it is not O.K., help me to understand what exactly might be wrong, please.

Cheers
K.


ping @rdebusscher  / this PR has been ready for review

**Pull request merged**
