### PR TITLE
Allow selection of Runtime without selecting MP Version. Fixes #173.

### LINKED ISSUE #173: When MPVersion is selected and deselected, Servers dropdown remains enabled
output

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Comment by Karm** [comment]
@rdebusscher  I cannot reproduce it though. It is possible that the tab had a view not refreshed while the server restarted....

**Comment by Karm** [comment]
@rdebusscher I hit the issue again. Steps to reproduce:

* open https://test-start.microprofile.io/
* click around, download something
* go for lunch 
* click selection boxes again, (or download button) you get the warning that session expired
* refresh (F5 in Firefox)
* you are redirected to https://test-start.microprofile.io/index.xhtml   (note the index.xhtml at the end) and you get Internal Server Error
* hitting F5 again, refreshing, brings the page back up again

Can we do something about it? The JSF is well beyond me, I have no idea frankly what happens with the lost context and why refresh causes the error instead of loading it anew.

**Comment by rdebusscher** [comment]
@Karm  I have a look at it. Maybe it has to do with the session expired which is not entirely correct.

I'll create another issue for this as it is not related to changes in this PR.

**Comment by Karm** [comment]
@rdebusscher THX.  I'll merge this now since it is not related.

**Comment by Karm** [comment]
There are 2 acks. Merging.

**Pull request merged**
