### PR TITLE
chore: Upgrade to OpenLiberty 19.0.0.12

### PR DESCRIPTION
**Pull request by cchacin**
Signed-off-by: Carlos Chacin <cchacin@gmail.com>

### CODE REVIEW

**Comment by rdebusscher** [comment]
Hi @cchacin 

Can you also create an issue and describe why this update is needed.

Thanks
Rudy

**Comment by Karm** [comment]
@rdebusscher I find it O.K. if it updates to a higher version...

**Comment by rdebusscher** [comment]
It is already a range and selects the latest one from maven. So I don't see the point WHY this is needed.

**Comment by Karm** [comment]
@rdebusscher  I see. IMHO this should be closed then.

**Comment by Karm** [comment]
@cchacin 
if you download Liberty example from our Starter page, you get:

```
[INFO] 
[INFO] --- liberty-maven-plugin:3.1:create (package-server) @ demo ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:20.0.0.1:zip.
[INFO] CWWKM2102I: Using installDirectory : /tmp/demo/target/liberty/wlp.
[INF
```

This PR is not needed.

**Comment by Emily-Jiang** [comment]
Agreed!

**Pull request closed without merging**
