### PR TITLE
Fix build issues for MP starter

### PR DESCRIPTION
**Pull request by breakponchito**
Fixing issues to execute build tests

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@breakponchito there are many failures

**Comment by breakponchito** [comment]
> @breakponchito there are many failures

yeah checking what to do for the following error:
image

in all cases is the same issue

**Comment by breakponchito** [comment]
> @breakponchito there are many failures

@Emily-Jiang  I already upgrade the version for the upload-artifact to use v4, please run again the validations

**Comment by breakponchito** [comment]
@Emily-Jiang Could you help me to run again the tests? it seems  a network problem, on my local I can't reproduce same error

**Comment by breakponchito** [comment]
@Emily-Jiang please run again the validation. I'm testing to increment connect timeout and read timeout to minutes

**Review by Emily-Jiang — APPROVED** [review]
LGTM. We will merge this one as the test failure cannot be replicated locally. We will then deploy the starter app to Open Liberty in a separate issue #498. With that, we should be able to fix all of the test failures.

**Comment by Emily-Jiang** [comment]
We discussed at today's call and agreed to merge this PR for now.

**Pull request merged**
