### PR TITLE
Fix formatting issue description GraphQL. Fixes #387

### LINKED ISSUE #387: GraphQL description formatting inconsistency
The description of GraphQL in the support matrix has a slightly different format than the existing descriptions where it uses `:` as a separator. Existing descriptions use `-` as a separator.
 
"GraphQL: GraphQL is a query language for APIs and a library for fulfilling those queries with your existing data." vs "Metrics - Gather and create operational and business measurements for your microservices".

https://start.microprofile.io/api/4/supportMatrix

### PR DESCRIPTION
**Pull request by rdebusscher**

### CODE REVIEW

**Comment by rdebusscher** [comment]
This change will also enable GraphQL option in the JetBrains MP Starter plugin (as it expects a certain formatting)

**Review by Emily-Jiang — APPROVED** [review]

**Review by Emily-Jiang — APPROVED** [review]

**Review by Emily-Jiang — CHANGES_REQUESTED** [review]
You need to update the test as well as you have failed one of the tests.

**Comment by Emily-Jiang** [comment]
You missed this file change  src/test/resources/json_examples/v4/supportMatrix.json.segments

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Pull request merged**
