### PR TITLE
Adds a Docker multistage build and a Thorntail profile

### PR DESCRIPTION
**Pull request by Karm**
The commit adds Container directory with a comprehensive README.md covering
building and running the Docker image. Dockerfile sports a multi-stage build.

One can use mvn thorntail:run -Pthorntail for development.

See Container/start.sh for some Thorntail specific properties set at container runtime.

There is not technical reason why the runtime whould have to be Thorntail,
it can be replaced with a differnet server.

Signed-off-by: Michal Karm Babacek karm@fedoraproject.org

### CODE REVIEW

**Comment by Karm** [comment]
@rdebusscher This is ready for review/comments, including the decision whether such build stuff even belongs to this repo at all. I am not planning on adding more commits to this PR until prompted. Thx.

**Comment by rdebusscher** [comment]
@Karm Thx for the PR, but I don't know if it will be used.

They are still in the process to define how (and where) the application will be deployed. So not sure if it will be Docker-based.

If your work can be used, I will propose it to on the mailing-list as a possible solution.

**Comment by Karm** [comment]
@rdebusscher Sure. If it comes handy in one form or another, drop me a line and I can tailor it. I use mostly Rancher for orchestration, or just Docker Compose and Systemd for single-host deployment.
The image from this PR runs on AWS, with Systemd unit and Docker Compose, hidden behind Cloudflare https://microstarter.foci.life/ .

If it is not used at all that is also perfectly fine. Thanks for your comment.

**Comment by Emily-Jiang** [comment]
Can you open an issue to explain what you are trying to do? Then the pr links to that issue.

**Comment by cealsair** [comment]
I don't know if you saw my post on the MicroProfile Google group/forum, but Red Hat will be funding the start.microprofile.io site so I have started working with Karm about how to best run this application on the cloud. Karm has suggested making the app a Docker image since this will ease maintenance of the application. Now that Karm has a prototype working, I'm going to set up a call with Rudy and Ryan for next steps.  Thank you.

**Comment by rdebusscher** [comment]
@cealsair I must have missed that and can't find it now.

I have created issue https://github.com/eclipse/microprofile-starter/issues/13 for this PR.

**Comment by Karm** [comment]
(I was notified about a typo in Container/README.md. Fixed, squashed.)

**Comment by rdebusscher** [comment]
@Karm Not an Expert but why is the Docker image so complicated. (and it downloads a massive amount of files which I already have on my computer!)

`mvn package -Pthorntail ` produces a jar file, which can be executed by  `java -jar target/mp-starter-thorntail.jar`

So what about a simple java8 docker image, add the jar and execute it?

**Comment by OndrejM** [comment]
@Karm, @cealsair,

This effort looks very useful, thanks for sharing with others. However, I'm not sure if it's worth to undergo a review by the Eclipse Foundation as it brings a lot of dependencies. 

I recommend to leave this PR open to have a discussion over it, but in the end close the PR and keep the sources in a repository outside Eclipse. Maybe in a repo maintained by Red Hat (maybe within Smallrye?) since Red Hat is going to host the app. I'm not an expert on Eclipse IP reviews though, just my personal opinion.

**Comment by Karm** [comment]
@rdebusscher Thank you for the feedback.
I split the build into two, one for development iterations and one for dependency-free ephemeral CI.
Check out the described workflow, please:
 * [Simple build adds just a few megabytes](https://github.com/eclipse/microprofile-starter/blob/12b1197163741010ea2f0cd38b900b440ef2f876/Container/README.md#docker-build
) of the war file.
 * And I recorded the session for you: see [doc](https://github.com/eclipse/microprofile-starter/blob/12b1197163741010ea2f0cd38b900b440ef2f876/Container/README.md#example-flow)
First build takes longer as you don't have the layers cached locally.

The CircleCI automated build can use the dependency free version that does its own maven etc.: See [doc](https://github.com/eclipse/microprofile-starter/blob/12b1197163741010ea2f0cd38b900b440ef2f876/Container/README.md#building-an-image).

**Comment by Karm** [comment]
@OndrejM 
Hello Ondrej,
thank you for the feedback.
This PR deals with running the application locally and with its deployment to the [https://test-start.microprofile.io/index.xhtml](https://test-start.microprofile.io/index.xhtml), soon start.microprofile.io.

Regarding you remark on bringing dependencies
--------
The PR brings 0 dependencies to the application itself, which is already heavy with JSF as it is. The PR merely adds a *thorntail* Maven profile and that brings Thorntail dependencies for those who wish to run the application with Thorntail.  I am happy to add other servers if there is a demand for that.

Docker
--------
The Docker build is irrelevant to the application code itself, so I moved all Docker related files into Container sub directory. There is also a comprehensive README.md describing the build within that directory.

CircleCI
-----------------------------
As a next step, I would like to provide CircleCI  yaml descriptor and ask Emily to configure a webhook so as releases on this repository are directly deployed to the live server.

What to do with this PR
-----------------------------
If it is seen as a better fit, the whole Container directory and the soon-to-come CircleCI yaml could live in a separate GitHub repository, using eclipse/microprofile-starter as a git submodule.

Although patching pom.xml on each build would add unnecessary friction, so I really do believe the pom.xml changes should remain in this repository.  As I stated before, if anyone would like to see a different server than Thorntail in the pom.xml as a profile, I am happy to oblige.

**Comment by Emily-Jiang** [comment]
I had a look at the PR and it looks good. We need to host the starter somewhere. @Karm chooses wildfly, which is fine. I cannot see any extra dependencies introduced by pom.xml. I think the only thing is to use wildfly app server.  Our conference apps already pull in app servers. I don't see any more complication on this. @OndrejM please clarify what other dependencies you are think where I missed.

**Comment by Karm** [comment]
@Emily-Jiang @OndroMih 
This PR is floating in some kind of limbo. if you have any feedback I can implement of refactor, please do share it. if you do not think this PR belongs to this repository it is a perfectly valid statement to make and we can close it. As the matter stands right now, I do not know whether you expect me do change something or what we are waiting for :smile:

**Comment by Emily-Jiang** [comment]
@Karm can you also add the Open Liberty profile where you can copy from service-mesh-service-a repo https://github.com/eclipse/microprofile-service-mesh-service-a/

**Comment by rdebusscher** [comment]
@Emily-Jiang What is the reason for also adding Open Liberty? We can only run the app on one implementation for the site.

If we want the people to give the option to run this locally on their computer (and choose what they use), we should also add Payara Micro, Kumuluzee and Apache TomEE.

**Pull request merged**
