### PR TITLE
Adds Microprofile favicon

### PR DESCRIPTION
**Pull request by Karm**
I received a zip file from @rstjames with png files and single layer ico files and some xml and json metadata. I am not really a frontend person, I don't know which JS API to use to present various icons to different browsers or whatnot, so I baked a 3 layered ico file with layers 16x16, 32x32, 96x96. It works for me in Firefox, the browser uses the smallest one on tabs and the largest one in tiled view of bookmarks.

Feel free to educate me on what is a better thing to do here.

screenshot

Addresses #72 

Signed-off-by: Michal Karm Babacek <karm@fedoraproject.org>

### CODE REVIEW

**Comment by rstjames** [comment]
@Karm The fav icon in the screenshot looks a bit off... Maybe I need to reformat the file also it would be best to use a png so that there is no white background . I will attach a new file today.

**Comment by Karm** [comment]
@rstjames O.K. .ico can be transparent, but I probably butchered it. Thank you for the help on this. Not sure one can have layers of different resolutions within png though, that's why I used ico...

**Comment by Karm** [comment]
@rdebusscher IMHO this can make it to the 0.8 release...?

**Comment by rstjames** [comment]
@Karm  Lets try this and see if it looks better. There is a .ico file. Plus all png ... lets see what works best. 
[MP_fav-icon.zip](https://github.com/eclipse/microprofile-starter/files/2835549/MP_fav-icon.zip)

**Comment by Karm** [comment]
@rstjames Excellent. I think it is much better now :+1: 

screenshot

**Comment by rdebusscher** [comment]
Merge into master as 0.8 is live for 6 days

**Pull request merged**
