### PR TITLE
MP 4.1 support (including @Startup example)

### PR DESCRIPTION
**Pull request by rdebusscher**
When selecting Quarkus, I get the following Maven error when compiling the generated project

```
Cannot resolve io.vertx:vertx-jwt:4.1.3

```

This seems to come from the Quarkus BOM dependency.

### CODE REVIEW

**Comment by Karm** [comment]
@rdebusscher Lemme take a look...

**Review by Emily-Jiang — APPROVED** [review]

**Comment by rdebusscher** [comment]
Tests keeps on failing on OpenLiberty.

**Comment by Emily-Jiang** [comment]
I will debug this locally after JakartaOne talk on Tuesday.

**Comment by rdebusscher** [comment]
OpenLiberty tests do work locally, merging.

**Pull request merged**
