### PR TITLE
Liberty config 

### PR DESCRIPTION
**Pull request by Emily-Jiang**

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
Please review and merge.

**Comment by rdebusscher** [comment]
No point in reviewing this as it is already online.

**Comment by Karm** [comment]
@rdebusscher On the contrary, it was pushed online from a temporary branch: https://github.com/eclipse/microprofile-starter/tree/v0.9.4+issue-211
  
Whether we want it in master in this shape and form is debatable and open for review.

**Comment by Karm** [comment]
@Emily-Jiang I am about to open a new PR that consolidates this (and makes it even simpler) and re-intoridces the artifact id division to service-a and b (correctly this time) and addresses similar issues for Helidon.

While testing it, I noticed that jwt does not work for Helidon and I am in touch with someone to help me nail it down.

**Comment by Emily-Jiang** [comment]
You can merge my changes and work on top of it if you want.

**Comment by Karm** [comment]
This PR is included in #214

**Pull request closed without merging**
