### PR TITLE
#281 add tracer for Open Liberty

### PR DESCRIPTION
**Pull request by Emily-Jiang**
Signed-off-by: Emily Jiang <emijiang6@googlemail.com>

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@Karm I could not run the test locally. The errors I got has nothing to do with my changes. Can you take a look and pull my changes into your repo to see whether you can get the tests to pass and then we can work out why the infrasture is not stable.

**Comment by Karm** [comment]
@Emily-Jiang Lemme re-run the tests, but this change is obviously Payara unrelated.

While you are adding Jaeger, don't you wirsh to copy-paste what is in Quarkus' readme.md and index.html about OpenTracing? There are notes for users on how to start Jaeger and on which port it listens...

**Comment by Emily-Jiang** [comment]
@Karm good idea, I will add some readme notes.

**Comment by Karm** [comment]
@Emily-Jiang  Is this ready for merge? Are you going to do anything else with the readme.md/index.html?

**Comment by Karm** [comment]
Fixes #281

**Comment by Emily-Jiang** [comment]
I have not managed to push to the test server as yet. Yes, I plan to add readme soon.

**Pull request merged**
