### PR TITLE
Fixes Warning for OpenLiberty related to OpenAPI document.

### PR DESCRIPTION
**Pull request by rdebusscher**
This solution only affects OpenLiberty and not other implementations so that Schema is not inlined.

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@rdebusscher I think the current open api demonstration does not demonstrate a good usage because the javadoc says very clearly that `ref` and the other attributes should not be used together. I think we should demo some best practices.

**Review by Emily-Jiang — CHANGES_REQUESTED** [review]
I think this PR defeats the purpose of having the same app running on all runtime. -1 on diverge the code base.

**Comment by rdebusscher** [comment]
> I think we should demo some best practices.

Best practices also means that OpenAPI document should use schemas and ref and not inline everything. (as #414 does)

It was fine with MP 3.3 but stopped working for 4.0 on OpenLiberty.

**Comment by rdebusscher** [comment]
>I think this PR defeats the purpose of having the same app running on all runtime. -1 on diverge the code base.

We have already several exceptions on this principal  since current spec allows these kind of differences, even for hello world like applications as this starter is using. We generate a project specific for each implementation.

**Comment by Emily-Jiang** [comment]
> > I think this PR defeats the purpose of having the same app running on all runtime. -1 on diverge the code base.
> 
> We have already several exceptions on this principal since current spec allows these kind of differences, even for hello world like applications as this starter is using. We generate a project specific for each implementation.

I don't think we generate different class file though. If this is the case, we need to look at each individual one and fix them up.

**Comment by rdebusscher** [comment]
Closing this PR. Update will be made to #414 to keep ref (and remove implementation property)

**Pull request closed without merging**
