### PR TITLE
Add try/catch to pemParser, fixed #106

### LINKED ISSUE #106: Resource leak: 'pemParser' is never closed
Resource leak: 'pemParser' is never closed in /src/test/java/<<package>>/JWTClient.java

### PR DESCRIPTION
**Pull request by hpragt**

### CODE REVIEW

**Comment by rdebusscher** [comment]
You have also created a Draft PR which cannot be merged.

**Comment by hpragt** [comment]
> 
> 
> Hi @hpragt ,
> 
> Thanks for your contribution. However, you are missing the signed-off-by in the commit message (see also https://www.eclipse.org/legal/ECA.php)

I added sign-off to commit message. What can I do now to let you receive the change ?

**Comment by rdebusscher** [comment]
Hi @hpragt 

It seems that the ECA form is not yet signed (linked to the email address you used in the commit). Can you do this?

Thx
Rudy

**Comment by Karm** [comment]
# ECA
Hello, @hpragt, we would like to process your contribution but your ECA  seems to be unsigned.

pragt

Make sure you signed it for your email address, see example of my profile:

karm_eca

Open https://accounts.eclipse.org/user and create an account and sign ECA, if that is what you want to do.

# Commits

Next, could you squash those commits into 1? e.g.

Either from scratch if you already deleted the repo locally:
```
$ git clone https://github.com/hpragt/microprofile-starter.git
$ cd microprofile-starter/
$ git remote  add upstream https://github.com/eclipse/microprofile-starter.git
$ git fetch --all
$ git rebase -i upstream/master

pick 7fafaae Add try/catch to pemParser
s a5b60ad Add try/catch to pemParser
# Rebase d5bc85d..873021b onto d5bc85d (2 command(s))
```
or with something like 
```git rebase -i HEAD~2```

Then edit the commit message so as it is one:

```
    Add try/catch to pemParser
    
    Signed-off-by: hpragt <github@pragt.org>
```

And force push to your remote origin branch:
```
git push origin 106 --force
```
The change will appear here on this PR and we can merge it :smiley: 


Thank you

**Comment by Karm** [comment]
@hpragt  ?

**Comment by rdebusscher** [comment]
Cannot be merged any longer since code is rewritten in #188.

**Comment by Karm** [comment]
Closing as obsoleted.

**Pull request closed without merging**
